-- Name: [SCHEMA] T-002 B-05 ROLLBACK (v2) - remove the flashcards and notes course triggers, the function and the composite keys
--
-- Description: PERSISTENT DDL, the undo of B-05_SCHEMA_flashcards-notes-course-derive_v1.sql. Run as ONE selection AFTER the B-06a and any later rollback and BEFORE B-04a_ROLLBACK (undo order for the stream: B-06a,
-- B-05, B-04a, B-07, B-03, B-02b, B-02a, B-01). v2 (QA Round 81, non-blocking 2): before dropping anything it binds the function (body hash, owner, security mode, search_path, ACL, language, result, volatility, exactly two triggers using it), each composite key (relation, definition, NOT VALID, referenced table, actions, match type) and both triggers (exact definition, enabled), and the other triggers and constraints of both tables to the recorded D2 set; it drops the two keys, the two triggers and the function, and raises unless the end state is exactly the recorded pre-B-05 state.
-- Values the triggers already derived stay as they are (they equal the subject's discipline). Existing columns, rows and the older triggers are not touched. Not run unless the Founder decides to undo B-05.

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';

LOCK TABLE public.flashcards, public.notes IN SHARE ROW EXCLUSIVE MODE;

DO $guard$
DECLARE
  v text;
BEGIN
  IF current_user <> 'postgres' OR session_user <> 'postgres' THEN
    RAISE EXCEPTION 'stopped: run this file as the migration owner postgres (current_user %, session_user %)', current_user, session_user;
  END IF;
  IF (SELECT count(*) FROM pg_trigger t WHERE t.tgenabled = 'O' AND NOT t.tgisinternal AND t.tgrelid = 'public.flashcards'::regclass
        AND t.tgname = 'trg_flashcards_course_derive_guard' AND pg_get_triggerdef(t.oid) = 'CREATE TRIGGER trg_flashcards_course_derive_guard BEFORE INSERT OR UPDATE OF subject_id, discipline_id, target_course ON public.flashcards FOR EACH ROW EXECUTE FUNCTION fn_course_derive_guard()') <> 1
     OR (SELECT count(*) FROM pg_trigger t WHERE t.tgenabled = 'O' AND NOT t.tgisinternal AND t.tgrelid = 'public.notes'::regclass
        AND t.tgname = 'trg_notes_course_derive_guard' AND pg_get_triggerdef(t.oid) = 'CREATE TRIGGER trg_notes_course_derive_guard BEFORE INSERT OR UPDATE OF subject_id, discipline_id, target_course ON public.notes FOR EACH ROW EXECUTE FUNCTION fn_course_derive_guard()') <> 1 THEN
    RAISE EXCEPTION 'B-05 ROLLBACK stopped: the two B-05 triggers are not the exact enabled B-05 triggers (or are already removed)';
  END IF;
  SELECT 'owner=' || pg_get_userbyid(p.proowner) || '; secdef=' || p.prosecdef || '; config=' || coalesce(p.proconfig::text, '-') || '; acl=' || coalesce(p.proacl::text, '-')
         || '; language=' || (SELECT l.lanname FROM pg_language l WHERE l.oid = p.prolang) || '; result=' || pg_get_function_result(p.oid) || '; volatility=' || p.provolatile::text
         || '; body_md5_without_carriage_returns=' || md5(replace(p.prosrc, chr(13), ''))
    INTO v FROM pg_proc p WHERE p.oid = to_regprocedure('public.fn_course_derive_guard()');
  IF v IS DISTINCT FROM 'owner=postgres; secdef=true; config={"search_path=pg_catalog, public"}; acl={postgres=X/postgres}; language=plpgsql; result=trigger; volatility=v; body_md5_without_carriage_returns=0d633f1e0410f0a1271880ce183fdc7d' THEN
    RAISE EXCEPTION 'B-05 ROLLBACK stopped: the function is not the B-05 function. Live: %', coalesce(v, '(missing)');
  END IF;
  IF (SELECT count(*) FROM pg_trigger WHERE tgfoid = to_regprocedure('public.fn_course_derive_guard()')::oid) <> 2 THEN
    RAISE EXCEPTION 'B-05 ROLLBACK stopped: the function is attached to a trigger other than the two B-05 triggers';
  END IF;
  SELECT pg_get_constraintdef(c.oid) || '|' || c.convalidated::text || '|' || c.contype::text || '|' || (c.confrelid = 'public.subjects'::regclass)::text || '|' || c.confupdtype::text || c.confdeltype::text || c.confmatchtype::text
    INTO v FROM pg_constraint c WHERE c.conrelid = 'public.flashcards'::regclass AND c.conname = 'flashcards_discipline_subject_fkey';
  IF v IS DISTINCT FROM 'FOREIGN KEY (discipline_id, subject_id) REFERENCES subjects(discipline_id, id) NOT VALID|false|f|true|aas' THEN
    RAISE EXCEPTION 'B-05 ROLLBACK stopped: flashcards_discipline_subject_fkey is not the B-05 key. Live: %', coalesce(v, '(missing)');
  END IF;
  SELECT pg_get_constraintdef(c.oid) || '|' || c.convalidated::text || '|' || c.contype::text || '|' || (c.confrelid = 'public.subjects'::regclass)::text || '|' || c.confupdtype::text || c.confdeltype::text || c.confmatchtype::text
    INTO v FROM pg_constraint c WHERE c.conrelid = 'public.notes'::regclass AND c.conname = 'notes_discipline_subject_fkey';
  IF v IS DISTINCT FROM 'FOREIGN KEY (discipline_id, subject_id) REFERENCES subjects(discipline_id, id) NOT VALID|false|f|true|aas' THEN
    RAISE EXCEPTION 'B-05 ROLLBACK stopped: notes_discipline_subject_fkey is not the B-05 key. Live: %', coalesce(v, '(missing)');
  END IF;
  IF (SELECT string_agg(tgname || '|' || pg_get_triggerdef(oid), ';' ORDER BY tgname COLLATE "C") FROM pg_trigger WHERE tgrelid = 'public.flashcards'::regclass AND NOT tgisinternal AND tgname <> 'trg_flashcards_course_derive_guard') IS DISTINCT FROM $lit$trg_aaa_counter_flashcards|CREATE TRIGGER trg_aaa_counter_flashcards AFTER INSERT OR DELETE ON public.flashcards FOR EACH ROW EXECUTE FUNCTION fn_update_flashcards_counter();trg_auto_resolve_flashcard_flags|CREATE TRIGGER trg_auto_resolve_flashcard_flags AFTER UPDATE ON public.flashcards FOR EACH ROW EXECUTE FUNCTION auto_resolve_content_error_flags('flashcard');trg_badge_flashcard_create|CREATE TRIGGER trg_badge_flashcard_create AFTER INSERT ON public.flashcards FOR EACH ROW EXECUTE FUNCTION fn_badge_check_flashcards();trg_cleanup_orphan_batch_provenance|CREATE TRIGGER trg_cleanup_orphan_batch_provenance AFTER UPDATE ON public.flashcards REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION fn_cleanup_orphan_batch_provenance();trg_guard_flashcard_batch_move|CREATE TRIGGER trg_guard_flashcard_batch_move BEFORE UPDATE OF batch_id ON public.flashcards FOR EACH ROW WHEN ((old.batch_id IS DISTINCT FROM new.batch_id)) EXECUTE FUNCTION fn_guard_flashcard_batch_move();trg_guard_flashcards_is_verified|CREATE TRIGGER trg_guard_flashcards_is_verified BEFORE INSERT OR UPDATE ON public.flashcards FOR EACH ROW EXECUTE FUNCTION fn_guard_flashcards_is_verified();trigger_update_deck_card_count|CREATE TRIGGER trigger_update_deck_card_count AFTER INSERT OR DELETE OR UPDATE OF deck_id ON public.flashcards FOR EACH ROW EXECUTE FUNCTION update_deck_card_count()$lit$
     OR (SELECT string_agg(tgname || '|' || pg_get_triggerdef(oid), ';' ORDER BY tgname COLLATE "C") FROM pg_trigger WHERE tgrelid = 'public.notes'::regclass AND NOT tgisinternal AND tgname <> 'trg_notes_course_derive_guard') IS DISTINCT FROM $lit$trg_aaa_counter_notes|CREATE TRIGGER trg_aaa_counter_notes AFTER INSERT OR DELETE ON public.notes FOR EACH ROW EXECUTE FUNCTION fn_update_notes_counter();trg_auto_resolve_note_flags|CREATE TRIGGER trg_auto_resolve_note_flags AFTER UPDATE ON public.notes FOR EACH ROW EXECUTE FUNCTION auto_resolve_content_error_flags('note');trg_autoclear_featured_notes|CREATE TRIGGER trg_autoclear_featured_notes BEFORE UPDATE ON public.notes FOR EACH ROW EXECUTE FUNCTION fn_autoclear_featured_on_visibility_change();trg_badge_note_upload|CREATE TRIGGER trg_badge_note_upload AFTER INSERT ON public.notes FOR EACH ROW EXECUTE FUNCTION fn_badge_check_notes();trg_guard_notes_privileged_columns|CREATE TRIGGER trg_guard_notes_privileged_columns BEFORE INSERT OR UPDATE ON public.notes FOR EACH ROW EXECUTE FUNCTION fn_guard_notes_decks_privileged_columns();trg_require_note_provenance|CREATE TRIGGER trg_require_note_provenance BEFORE INSERT ON public.notes FOR EACH ROW EXECUTE FUNCTION fn_require_note_provenance()$lit$
     OR (SELECT string_agg(conname || '|' || pg_get_constraintdef(oid), ';' ORDER BY conname COLLATE "C") FROM pg_constraint WHERE conrelid = 'public.flashcards'::regclass AND conname <> 'flashcards_discipline_subject_fkey') IS DISTINCT FROM $lit$chk_flashcards_question_type|CHECK ((question_type = ANY (ARRAY['flashcard'::text, 'mcq'::text, 'correct_incorrect'::text, 'theory'::text, 'case_study_mcq'::text, 'match_the_following'::text, 'fitb'::text, 'concept_card'::text, 'mcq_multi'::text])));chk_flashcards_source|CHECK ((source = ANY (ARRAY['manual'::text, 'gemini_import'::text, 'bulk_upload'::text])));flashcards_content_creator_id_fkey|FOREIGN KEY (content_creator_id) REFERENCES content_creators(id);flashcards_contributed_by_fkey|FOREIGN KEY (contributed_by) REFERENCES profiles(id) ON DELETE SET NULL;flashcards_creator_id_fkey|FOREIGN KEY (creator_id) REFERENCES profiles(id) ON DELETE SET NULL;flashcards_deck_id_fkey|FOREIGN KEY (deck_id) REFERENCES flashcard_decks(id) ON DELETE SET NULL;flashcards_difficulty_check|CHECK ((difficulty = ANY (ARRAY['easy'::text, 'medium'::text, 'hard'::text])));flashcards_discipline_id_fkey|FOREIGN KEY (discipline_id) REFERENCES disciplines(id);flashcards_note_id_fkey|FOREIGN KEY (note_id) REFERENCES notes(id) ON DELETE SET NULL;flashcards_pkey|PRIMARY KEY (id);flashcards_subject_id_fkey|FOREIGN KEY (subject_id) REFERENCES subjects(id);flashcards_topic_id_fkey|FOREIGN KEY (topic_id) REFERENCES topics(id);flashcards_user_id_fkey|FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;flashcards_visibility_check|CHECK ((visibility = ANY (ARRAY['private'::text, 'friends'::text, 'public'::text])))$lit$
     OR (SELECT string_agg(conname || '|' || pg_get_constraintdef(oid), ';' ORDER BY conname COLLATE "C") FROM pg_constraint WHERE conrelid = 'public.notes'::regclass AND conname <> 'notes_discipline_subject_fkey') IS DISTINCT FROM $lit$notes_check|CHECK (((is_featured_on_landing = false) OR (visibility = 'public'::text)));notes_content_source_type_check|CHECK (((content_source_type IS NULL) OR (content_source_type = ANY (ARRAY['official_body'::text, 'original_creator'::text]))));notes_content_type_check|CHECK ((content_type = ANY (ARRAY['text'::text, 'table'::text, 'math'::text, 'diagram'::text, 'mixed'::text])));notes_contributed_by_fkey|FOREIGN KEY (contributed_by) REFERENCES profiles(id) ON DELETE SET NULL;notes_discipline_id_fkey|FOREIGN KEY (discipline_id) REFERENCES disciplines(id);notes_featured_approved_by_fkey|FOREIGN KEY (featured_approved_by) REFERENCES profiles(id) ON DELETE SET NULL;notes_featured_nominated_by_fkey|FOREIGN KEY (featured_nominated_by) REFERENCES profiles(id) ON DELETE SET NULL;notes_pkey|PRIMARY KEY (id);notes_subject_id_fkey|FOREIGN KEY (subject_id) REFERENCES subjects(id);notes_topic_id_fkey|FOREIGN KEY (topic_id) REFERENCES topics(id);notes_user_id_fkey|FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;notes_visibility_check|CHECK ((visibility = ANY (ARRAY['private'::text, 'friends'::text, 'public'::text])))$lit$ THEN
    RAISE EXCEPTION 'B-05 ROLLBACK stopped: the other triggers or constraints of flashcards or notes are not the recorded pre-B-05 set (D2)';
  END IF;
END
$guard$;

ALTER TABLE public.flashcards DROP CONSTRAINT flashcards_discipline_subject_fkey;
ALTER TABLE public.notes DROP CONSTRAINT notes_discipline_subject_fkey;
DROP TRIGGER trg_flashcards_course_derive_guard ON public.flashcards;
DROP TRIGGER trg_notes_course_derive_guard ON public.notes;
DROP FUNCTION public.fn_course_derive_guard();

DO $postcheck$
BEGIN
  IF (SELECT string_agg(tgname || '|' || pg_get_triggerdef(oid), ';' ORDER BY tgname COLLATE "C") FROM pg_trigger WHERE tgrelid = 'public.flashcards'::regclass AND NOT tgisinternal) IS DISTINCT FROM $lit$trg_aaa_counter_flashcards|CREATE TRIGGER trg_aaa_counter_flashcards AFTER INSERT OR DELETE ON public.flashcards FOR EACH ROW EXECUTE FUNCTION fn_update_flashcards_counter();trg_auto_resolve_flashcard_flags|CREATE TRIGGER trg_auto_resolve_flashcard_flags AFTER UPDATE ON public.flashcards FOR EACH ROW EXECUTE FUNCTION auto_resolve_content_error_flags('flashcard');trg_badge_flashcard_create|CREATE TRIGGER trg_badge_flashcard_create AFTER INSERT ON public.flashcards FOR EACH ROW EXECUTE FUNCTION fn_badge_check_flashcards();trg_cleanup_orphan_batch_provenance|CREATE TRIGGER trg_cleanup_orphan_batch_provenance AFTER UPDATE ON public.flashcards REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION fn_cleanup_orphan_batch_provenance();trg_guard_flashcard_batch_move|CREATE TRIGGER trg_guard_flashcard_batch_move BEFORE UPDATE OF batch_id ON public.flashcards FOR EACH ROW WHEN ((old.batch_id IS DISTINCT FROM new.batch_id)) EXECUTE FUNCTION fn_guard_flashcard_batch_move();trg_guard_flashcards_is_verified|CREATE TRIGGER trg_guard_flashcards_is_verified BEFORE INSERT OR UPDATE ON public.flashcards FOR EACH ROW EXECUTE FUNCTION fn_guard_flashcards_is_verified();trigger_update_deck_card_count|CREATE TRIGGER trigger_update_deck_card_count AFTER INSERT OR DELETE OR UPDATE OF deck_id ON public.flashcards FOR EACH ROW EXECUTE FUNCTION update_deck_card_count()$lit$
     OR (SELECT string_agg(tgname || '|' || pg_get_triggerdef(oid), ';' ORDER BY tgname COLLATE "C") FROM pg_trigger WHERE tgrelid = 'public.notes'::regclass AND NOT tgisinternal) IS DISTINCT FROM $lit$trg_aaa_counter_notes|CREATE TRIGGER trg_aaa_counter_notes AFTER INSERT OR DELETE ON public.notes FOR EACH ROW EXECUTE FUNCTION fn_update_notes_counter();trg_auto_resolve_note_flags|CREATE TRIGGER trg_auto_resolve_note_flags AFTER UPDATE ON public.notes FOR EACH ROW EXECUTE FUNCTION auto_resolve_content_error_flags('note');trg_autoclear_featured_notes|CREATE TRIGGER trg_autoclear_featured_notes BEFORE UPDATE ON public.notes FOR EACH ROW EXECUTE FUNCTION fn_autoclear_featured_on_visibility_change();trg_badge_note_upload|CREATE TRIGGER trg_badge_note_upload AFTER INSERT ON public.notes FOR EACH ROW EXECUTE FUNCTION fn_badge_check_notes();trg_guard_notes_privileged_columns|CREATE TRIGGER trg_guard_notes_privileged_columns BEFORE INSERT OR UPDATE ON public.notes FOR EACH ROW EXECUTE FUNCTION fn_guard_notes_decks_privileged_columns();trg_require_note_provenance|CREATE TRIGGER trg_require_note_provenance BEFORE INSERT ON public.notes FOR EACH ROW EXECUTE FUNCTION fn_require_note_provenance()$lit$
     OR (SELECT string_agg(conname || '|' || pg_get_constraintdef(oid), ';' ORDER BY conname COLLATE "C") FROM pg_constraint WHERE conrelid = 'public.flashcards'::regclass) IS DISTINCT FROM $lit$chk_flashcards_question_type|CHECK ((question_type = ANY (ARRAY['flashcard'::text, 'mcq'::text, 'correct_incorrect'::text, 'theory'::text, 'case_study_mcq'::text, 'match_the_following'::text, 'fitb'::text, 'concept_card'::text, 'mcq_multi'::text])));chk_flashcards_source|CHECK ((source = ANY (ARRAY['manual'::text, 'gemini_import'::text, 'bulk_upload'::text])));flashcards_content_creator_id_fkey|FOREIGN KEY (content_creator_id) REFERENCES content_creators(id);flashcards_contributed_by_fkey|FOREIGN KEY (contributed_by) REFERENCES profiles(id) ON DELETE SET NULL;flashcards_creator_id_fkey|FOREIGN KEY (creator_id) REFERENCES profiles(id) ON DELETE SET NULL;flashcards_deck_id_fkey|FOREIGN KEY (deck_id) REFERENCES flashcard_decks(id) ON DELETE SET NULL;flashcards_difficulty_check|CHECK ((difficulty = ANY (ARRAY['easy'::text, 'medium'::text, 'hard'::text])));flashcards_discipline_id_fkey|FOREIGN KEY (discipline_id) REFERENCES disciplines(id);flashcards_note_id_fkey|FOREIGN KEY (note_id) REFERENCES notes(id) ON DELETE SET NULL;flashcards_pkey|PRIMARY KEY (id);flashcards_subject_id_fkey|FOREIGN KEY (subject_id) REFERENCES subjects(id);flashcards_topic_id_fkey|FOREIGN KEY (topic_id) REFERENCES topics(id);flashcards_user_id_fkey|FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;flashcards_visibility_check|CHECK ((visibility = ANY (ARRAY['private'::text, 'friends'::text, 'public'::text])))$lit$
     OR (SELECT string_agg(conname || '|' || pg_get_constraintdef(oid), ';' ORDER BY conname COLLATE "C") FROM pg_constraint WHERE conrelid = 'public.notes'::regclass) IS DISTINCT FROM $lit$notes_check|CHECK (((is_featured_on_landing = false) OR (visibility = 'public'::text)));notes_content_source_type_check|CHECK (((content_source_type IS NULL) OR (content_source_type = ANY (ARRAY['official_body'::text, 'original_creator'::text]))));notes_content_type_check|CHECK ((content_type = ANY (ARRAY['text'::text, 'table'::text, 'math'::text, 'diagram'::text, 'mixed'::text])));notes_contributed_by_fkey|FOREIGN KEY (contributed_by) REFERENCES profiles(id) ON DELETE SET NULL;notes_discipline_id_fkey|FOREIGN KEY (discipline_id) REFERENCES disciplines(id);notes_featured_approved_by_fkey|FOREIGN KEY (featured_approved_by) REFERENCES profiles(id) ON DELETE SET NULL;notes_featured_nominated_by_fkey|FOREIGN KEY (featured_nominated_by) REFERENCES profiles(id) ON DELETE SET NULL;notes_pkey|PRIMARY KEY (id);notes_subject_id_fkey|FOREIGN KEY (subject_id) REFERENCES subjects(id);notes_topic_id_fkey|FOREIGN KEY (topic_id) REFERENCES topics(id);notes_user_id_fkey|FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;notes_visibility_check|CHECK ((visibility = ANY (ARRAY['private'::text, 'friends'::text, 'public'::text])))$lit$
     OR to_regprocedure('public.fn_course_derive_guard()') IS NOT NULL THEN
    RAISE EXCEPTION 'B-05 ROLLBACK stopped: the end state is not exactly the recorded pre-B-05 state (D2 triggers and constraints of both tables, no B-05 function); nothing is applied';
  END IF;
END
$postcheck$;

SELECT (SELECT count(*) FROM pg_trigger WHERE tgrelid = 'public.flashcards'::regclass AND NOT tgisinternal) AS flashcards_triggers_expected_7,
       (SELECT count(*) FROM pg_trigger WHERE tgrelid = 'public.notes'::regclass AND NOT tgisinternal) AS notes_triggers_expected_6,
       to_regprocedure('public.fn_course_derive_guard()') IS NULL AS function_removed;
